const LOGOS = {
    // ── La Liga ────────────────────────────────────────────────────
    "Real Madrid":                  "assets/logos/real-madrid.png",
    "Alaves":                       "assets/logos/deportivo.png",
    "Deportivo Alavés":             "assets/logos/deportivo.png",
    "D. Alavés":                    "assets/logos/deportivo.png",
    "Levante":                      "assets/logos/levante.png",
    "Levante UD":                   "assets/logos/levante-ud.png",
    "Real Sociedad":                "assets/logos/real-sociedad.png",
    "RCD Mallorca":                 "assets/logos/rcd-mallorca.png",
    "Real Betis":                   "assets/logos/real-betis.png",
    "Real Betis Balompié":          "assets/logos/real-betis.png",
    "Valencia CF":                  "assets/logos/valencia-cf.png",
    "CA Osasuna":                   "assets/logos/ca-osasuna.png",
    "Athletic Club":                "assets/logos/athletic-club.png",
    "RCD Espanyol":                 "assets/logos/rcd-espanyol.png",
    "RCD Espanyol de Barcelona":    "assets/logos/rcd-espanyol.png",
    "Sevilla FC":                   "assets/logos/sevilla-fc.png",
    "FC Barcelona":                 "assets/logos/fc-barcelona.png",
    "SD Eibar":                     "assets/logos/sd-eibar.png",
    "Villarreal CF":                "assets/logos/villarreal-cf.png",
    "Getafe CF":                    "assets/logos/getafe-cf.png",
    "Elche CF":                     "assets/logos/elche-cf.png",
    "Girona FC":                    "assets/logos/girona-fc.png",
    "Atlético de Madrid":           "assets/logos/atletico-de-madrid.png",
    "Real Club Celta":              "assets/logos/real-club-celta.png",
    "Celta":                        "assets/logos/real-club-celta.png",
    "Real Club Celta de Vigo":      "assets/logos/real-club-celta.png",
    "Rayo Vallecano":               "assets/logos/rayo-vallecano.png",

    // ── UCL ────────────────────────────────────────────────────────
    "Marseille":                    "assets/logos/marseille.png",
    "Olympique de Marseille":       "assets/logos/marseille.png",
    "Manchester City":              "assets/logos/manchester-city.png",
    "Manchester United":            "assets/logos/manchester-united.png",
    "Man Utd":                      "assets/logos/manchester-united.png",
    "GNK Dinamo Zagreb":            "assets/logos/gnk-dinamo-zagreb.png",
    "Dinamo Zagreb":                "assets/logos/gnk-dinamo-zagreb.png",
    "SL Benfica":                   "assets/logos/sl-benfica.png",
    "Sporting CP":                  "assets/logos/sporting-cp.png",
    "Brøndby IF":                   "assets/logos/brondby.png",
    "Feyenoord":                    "assets/logos/feyenoord.png",
    "Qarabağ FK":                   "assets/logos/qarabag.png",
    "PSV":                          "assets/logos/psv.png",
    "Olympiacos FC":                "assets/logos/olympiacos.png",
    "Bayer 04 Leverkusen":          "assets/logos/bayer-leverkusen.png",
    "Borussia Dortmund":            "assets/logos/borussia-dortmund.png",
    "SK Slavia Praha":              "assets/logos/slavia-praha.png",
    "Slavia Praha":                 "assets/logos/slavia-praha.png",
    "FC Bayern München":            "assets/logos/bayern-munchen.png",
    "Fenerbahçe SK":                "assets/logos/fenerbahce.png",
    "Fenerbahçe":                   "assets/logos/fenerbahce.png",
    "Celtic":                       "assets/logos/celtic.png",
    "Rangers":                      "assets/logos/rangers.png",
    "AS Monaco":                    "assets/logos/as-monaco.png",
    "Galatasaray SK":               "assets/logos/galatasaray.png",
    "Galatasaray":                  "assets/logos/galatasaray.png",
    "Juventus":                     "assets/logos/juventus.png",
    "Inter Milan":                  "assets/logos/inter.png",
    "Arsenal":                      "assets/logos/arsenal.png",
    "Paris Saint-Germain":          "assets/logos/paris-saint-germain.png",
    "AC Milan":                     "assets/logos/milan.png",
    "BK Häcken":                    "assets/logos/bk-hacken.png",
    "RB Leipzig":                   "assets/logos/rb-leipzig.png",
    "Club Brugge":                  "assets/logos/club-brugge.png",
    "FK Bodø/Glimt":                "assets/logos/bodo-glimt.png",
    "Chelsea":                      "assets/logos/chelsea.png",
    "FC Red Bull Salzburg":         "assets/logos/salzburg.png",
    "AS Roma":                      "assets/logos/roma.png",

    // ── Loan clubs ─────────────────────────────────────────────────
    "Udinese":                      "assets/logos/udinese.png",
    "R Union St-g":                 "assets/logos/union-saint-gilloise.png",
    "LOSC Lille":                   "assets/logos/lille.png",
    "R. Union St.-G.":              "assets/logos/union-saint-gilloise.png",
    "F.C. København":               "assets/logos/copenhagen.png",
    "AEK Athens":                   "assets/logos/aek-athens.png",
    "Ferencvárosi TC":              "assets/logos/ferencvaros.png",
    "OM":                           "assets/logos/marseille.png",
    "Asteras AKTOR":                "assets/logos/asteras-aktor.png",
    "Club America":                 "assets/logos/club-america.png",
    "CD Guadalajara":               "assets/logos/cd-guadalajara.png",
    "Club Tijuana":                 "assets/logos/club-tijuana.svg",
    "Blau Weiss Linz":              "assets/logos/blau-weiss-linz.svg",
};

export function getClubLogo(name) {
    return LOGOS[name] ?? null;
}
